/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package App


import org.apache.spark.SparkConf
import org.apache.spark.sql.SparkSession

import com.salesforce.op.features.FeatureLike

object PackageTest {
  def main(args: Array[String]): Unit = {
    implicit val spark = SparkSession.builder.config(new SparkConf()).getOrCreate()
    import spark.implicits._
    spark.sparkContext.listJars.foreach(println)
  }

}
